DROP TABLE DETECCOES_MOTO;

CREATE TABLE DETECCOES_MOTO (
    ID_DETECCAO   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MOTO       NUMBER,
    POSICAO_X     NUMBER,
    POSICAO_Y     NUMBER,
    CONFIANCA     NUMBER(5,3),
    HORARIO_REGISTRO DATE DEFAULT SYSDATE
);

SELECT * FROM DETECCOES_MOTO;